// define TOKEN
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZDg1MmRlMy03MDQ1LTRjOWMtOTU4Ni0zMWM3ZWFiY2RjYzYiLCJyb2xlIjoiQ0xJRU5UIiwiaWF0IjoxNzc2NTMzODQ5LCJleHAiOjE3NzY1MzQ3NDl9.jgun3dlh99MKteck_2NdOQLo38ZWr9c7M_hGd--845U
@API_URL = http://localhost:8080/api/clients

// test registering a new client
###
POST {{API_URL}}/register
Content-Type: application/json


{
  "name": "Test Client",
  "email": "testclient1@example.com",
  "password": "password123"
}

// test logging in as the new client
###
POST {{API_URL}}/login
Content-Type: application/json

{
  "email": "aelshabrawy60@gmail.com",
  "password": "1522004aA"
}

### 
// test onboarding a client 
POST {{API_URL}}/onboard
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Test Client",
  "phone": "1234567890",
  "region": "Cairo"
}





// test discovering vendors as a client
###
GET {{API_URL}}/discover


// test adding a review as a client
###
POST {{API_URL}}/reviews
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "vendorId": "a21f20c6-c571-443b-bd4f-b3169a02fd18",
  "value": 5,
  "comment": "Great vendor!",
  "mediaUrls": ["https://example.com/review1.jpg", "https://example.com/review2.jpg"]
}


// test getting saved posts as a client
###
GET {{API_URL}}/saves
Authorization: Bearer {{TOKEN}}

// test saving a post as a client
###
POST {{API_URL}}/saves
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "postId": "3075338c-efe4-43e5-848e-75e099e4b2ea"
}

// test unsaving a post as a client
###
DELETE {{API_URL}}/saves
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "postId": "3075338c-efe4-43e5-848e-75e099e4b2ea"
}
