
// test registering a new vendor
###
POST http://localhost:8080/api/vendors/register
Content-Type: application/json

{
  "email": "testvendor4@example.com",
  "password": "password123"
}

###
// test logging in as the new vendor
POST http://localhost:8080/api/vendors/login
Content-Type: application/json

{
  "email": "testvendor2@example.com",
  "password": "password123"
}

###
// test onboarding a vendor

POST http://localhost:8080/api/vendors/onboard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGJmMTM5My1hMDkxLTQzZWUtOWRhZi0zOWE2NDc3M2Q1ZWEiLCJyb2xlIjoiVkVORE9SIiwiaWF0IjoxNzc1NzU0NzU0LCJleHAiOjE3NzU3NTU2NTR9.B-m1p4xAWbZKJCGJ0YZDTsjdB7qPpURG1oolpac7KhU

{ 
  "name": "Mohamed Gamal",
  "phone": "1234567890",
  "region": "Alexandria",
  "category": "Fashion",
  "experience": 3,
  "portfolioUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpozJ5j8gH5yMSc2sKne5teLdCvsM0MWDfkw&s",
  "profilePicture": "https://www.ziprecruiter.com/svc/fotomat/public-ziprecruiter/cms/889026084FreelancePhotographer.jpg=ws1280x960",
  "price": 1200,
  "type": 2,
  "about": "I'm a professional fashion photographer with 3 years of experience in commercial photography. Specializing in e-commerce and lifestyle product shots."
}


// test createing a portfolio post as a vendor
###
POST http://localhost:8080/api/vendors/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGJmMTM5My1hMDkxLTQzZWUtOWRhZi0zOWE2NDc3M2Q1ZWEiLCJyb2xlIjoiVkVORE9SIiwiaWF0IjoxNzc1NzU0NzU0LCJleHAiOjE3NzU3NTU2NTR9.B-m1p4xAWbZKJCGJ0YZDTsjdB7qPpURG1oolpac7KhU

{
  "hashtags": ["graphic design", "branding"],
  "mediaUrls": ["https://i.pinimg.com/736x/f4/5a/98/f45a98fefc03972f92f31cdbd24e0b9d.jpg"]
}


// test getting a vendor by id as a client
###
GET http://localhost:8080/api/clients/vendors/a21f20c6-c571-443b-bd4f-b3169a02fd18
